### ISSUE TITLE
最近版本的@swc/core构建报错

### ISSUE THREAD

**Issue by ayiaq1** [lonelyhentxi/swc-plugin-another-transform-imports#4]
版本： 
"@swc/core": "^1.3.62",
"swc-plugin-another-transform-imports": "^0.2.3"
报错提示：
<img width="1100" alt="image" src="https://github.com/lonelyhentxi/swc-plugin-another-transform-imports/assets/3860498/eee091ad-eea2-4be4-91eb-40bf63555db5">

**Comment by aitiotekt** [comment]
@ayiaq1 
Sorry for the late rely, I'm too busy. Try 0.2.4 for @swc/core >= 1.3.58, there are breaking changes.

**Comment by ayiaq1** [comment]
![image](https://github.com/lonelyhentxi/swc-plugin-another-transform-imports/assets/3860498/a9cf3699-71b2-4f44-b99f-63fc1edf3b8f)
<img width="840" alt="image" src="https://github.com/lonelyhentxi/swc-plugin-another-transform-imports/assets/3860498/460250c4-0918-46f0-b358-d93dca7841c0">

"@swc/core": "^1.3.63",
"swc-plugin-another-transform-imports": "^0.2.4",

是我配置有问题吗？

**Comment by aitiotekt** [comment]
> ![image](https://github.com/lonelyhentxi/swc-plugin-another-transform-imports/assets/3860498/a9cf3699-71b2-4f44-b99f-63fc1edf3b8f)
> <img width="840" alt="image" src="https://github.com/lonelyhentxi/swc-plugin-another-transform-imports/assets/3860498/460250c4-0918-46f0-b358-d93dca7841c0">
> 
> "@swc/core": "^1.3.63",
> "swc-plugin-another-transform-imports": "^0.2.4",
> 是我配置有问题吗？

In my test project, the plugin works well, https://github.com/lonelyhentxi/swc-plugin-another-transform-imports-test.

Your problem in above screenshot seems like a utf8 decoding error related to your own project or deps?
