### ISSUE TITLE
Support @swc/core@1.6.x

### ISSUE THREAD

**Issue by tony-scio** [lonelyhentxi/swc-plugin-another-transform-imports#6]
Thanks for the awesome library. Kindly requesting support for `@swc/core@1.6.x`.

**Comment by aitiotekt** [comment]
> Thanks for the awesome library. Kindly requesting support for `@swc/core@1.6.x`.

I bump all dependencies and publish new versions. 

And for `@swc/core@1.6.x` you can try `swc-plugin-another-transform-imports@1.6.0` 😊

**Comment by tony-scio** [comment]
Thanks so much! Confirmed that it's working w/ my project.
